{{- if .Values.global.includeS3 }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-minio
  labels:
    app: minio
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: minio
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minio
    spec:
      containers:
        - name: minio
          image: {{ .Values.infra.minio.image }}
          args:
            - server
            - /data
            - --console-address
            - :9001
          ports:
            - containerPort: 9000
              name: api
            - containerPort: 9001
              name: console
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-minio-secret
                  key: access-key-id
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-minio-secret
                  key: secret-access-key
      volumes:
        - name: data
          emptyDir: {} # Ephemeral storage for easy local setup
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-minio
  labels:
    app.kubernetes.io/name: minio
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.infra.minio.service.apiPort }}
      targetPort: 9000
      name: api
    - port: {{ .Values.infra.minio.service.consolePort }}
      targetPort: 9001
      name: console
  selector:
    app.kubernetes.io/name: minio
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-minio-setup
  labels:
    app: minio-setup
    release: {{ .Release.Name }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minio-setup
    spec:
      restartPolicy: OnFailure
      containers:
        - name: minio-setup
          image: quay.io/minio/mc:latest
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-minio-secret
                  key: access-key-id
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-minio-secret
                  key: secret-access-key
          command:
            - /bin/sh
            - -c
            - |
              # Wait for MinIO to be ready
              until mc alias set myminio http://{{ .Release.Name }}-minio:9000 $MINIO_ACCESS_KEY $MINIO_SECRET_KEY; do
                echo "Waiting for MinIO to be ready..."
                sleep 2
              done

              # Create bucket if it doesn't exist
              mc mb myminio/{{ .Values.infra.minio.bucket }} --ignore-existing

              echo "MinIO setup complete"
{{- end }}